import { EventEmitter, OnChanges, ElementRef, AfterViewInit } from '@angular/core';
export declare class XAxisTicks implements OnChanges, AfterViewInit {
    scale: any;
    orient: any;
    tickArguments: number[];
    tickStroke: string;
    tickFormatting: any;
    showGridLines: boolean;
    gridLineHeight: any;
    width: any;
    dimensionsChanged: EventEmitter<{}>;
    verticalSpacing: any;
    rotateLabels: any;
    innerTickSize: any;
    outerTickSize: any;
    tickPadding: any;
    textAnchor: any;
    maxTicksLength: any;
    maxAllowedLength: number;
    trimLabel: any;
    adjustedScale: any;
    tickValues: any;
    textTransform: any;
    ticks: any;
    tickFormat: any;
    height: number;
    ticksElement: ElementRef;
    constructor();
    ngOnChanges(): void;
    ngAfterViewInit(): void;
    updateDims(): void;
    update(): void;
    getRotationAngle(ticks: any): number;
    getTicks(): any;
    getMaxTicks(): number;
    tickTransform(tick: any): string;
    gridLineTransform(): string;
}
