import { EventEmitter, ElementRef, SimpleChanges, OnChanges } from '@angular/core';
import { Location } from '@angular/common';
export declare class BarComponent implements OnChanges {
    private location;
    fill: any;
    data: any;
    width: any;
    height: any;
    x: any;
    y: any;
    orientation: any;
    roundEdges: boolean;
    gradient: boolean;
    offset: number;
    isActive: boolean;
    stops: any[];
    select: EventEmitter<{}>;
    activate: EventEmitter<{}>;
    deactivate: EventEmitter<{}>;
    element: any;
    path: any;
    gradientId: any;
    gradientFill: any;
    startOpacity: any;
    initialized: boolean;
    gradientStops: any[];
    hasGradient: boolean;
    constructor(element: ElementRef, location: Location);
    ngOnChanges(changes: SimpleChanges): void;
    update(): void;
    loadAnimation(): void;
    animateToCurrentForm(): void;
    getGradient(): any[];
    getStartingPath(): any;
    getPath(): any;
    getRadius(): number;
    getStartOpacity(): number;
    roundedRect(x: any, y: any, w: any, h: any, r: any, tl: any, tr: any, bl: any, br: any): any;
    onMouseEnter(): void;
    onMouseLeave(): void;
}
