import { OnChanges, SimpleChanges, TemplateRef, EventEmitter } from '@angular/core';
export declare class PolarSeriesComponent implements OnChanges {
    name: any;
    data: any;
    xScale: any;
    yScale: any;
    colors: any;
    scaleType: any;
    curve: any;
    activeEntries: any[];
    rangeFillOpacity: number;
    tooltipDisabled: boolean;
    tooltipText: (o: any) => string;
    gradient: boolean;
    tooltipTemplate: TemplateRef<any>;
    animations: boolean;
    select: EventEmitter<{}>;
    activate: EventEmitter<{}>;
    deactivate: EventEmitter<{}>;
    path: string;
    circles: any[];
    circleRadius: number;
    outerPath: string;
    areaPath: string;
    gradientId: string;
    gradientUrl: string;
    hasGradient: boolean;
    gradientStops: any[];
    areaGradientStops: any[];
    seriesColor: string;
    active: boolean;
    inactive: boolean;
    ngOnChanges(changes: SimpleChanges): void;
    update(): void;
    getAngle(d: any): any;
    getRadius(d: any): any;
    getLineGenerator(): any;
    sortData(data: any): any;
    isActive(entry: any): boolean;
    isInactive(entry: any): boolean;
    defaultTooltipText({ label, value }: {
        label: any;
        value: any;
    }): string;
    updateGradients(): void;
}
