import { OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { Observable } from 'rxjs/Rx';
import { PieLabelOption } from '../src/common';
export declare class AppComponent implements OnInit {
    location: Location;
    version: string;
    theme: string;
    chartType: string;
    chartGroups: any[];
    chart: any;
    realTimeData: boolean;
    countries: any[];
    single: any[];
    multi: any[];
    dateData: any[];
    dateDataWithRange: any[];
    calendarData: any[];
    statusData: any[];
    graph: {
        links: any[];
        nodes: any[];
    };
    bubble: any;
    linearScale: boolean;
    range: boolean;
    view: any[];
    width: number;
    height: number;
    fitContainer: boolean;
    showXAxis: boolean;
    showYAxis: boolean;
    gradient: boolean;
    showLegend: boolean;
    legendTitle: string;
    showXAxisLabel: boolean;
    tooltipDisabled: boolean;
    xAxisLabel: string;
    showYAxisLabel: boolean;
    yAxisLabel: string;
    showGridLines: boolean;
    innerPadding: string;
    barPadding: number;
    groupPadding: number;
    roundDomains: boolean;
    maxRadius: number;
    minRadius: number;
    showSeriesOnHover: boolean;
    curveType: string;
    curve: any;
    interpolationTypes: string[];
    colorSets: any;
    colorScheme: any;
    schemeType: string;
    selectedColorScheme: string;
    rangeFillOpacity: number;
    showLabels: boolean;
    explodeSlices: boolean;
    doughnut: boolean;
    arcWidth: number;
    pieLabelOption: PieLabelOption;
    pieLabelOption$: Observable<PieLabelOption>;
    autoScale: boolean;
    timeline: boolean;
    margin: boolean;
    marginTop: number;
    marginRight: number;
    marginBottom: number;
    marginLeft: number;
    gaugeMin: number;
    gaugeMax: number;
    gaugeLargeSegments: number;
    gaugeSmallSegments: number;
    gaugeTextValue: string;
    gaugeUnits: string;
    gaugeAngleSpan: number;
    gaugeStartAngle: number;
    gaugeShowAxis: boolean;
    gaugeValue: number;
    gaugePreviousValue: number;
    constructor(location: Location);
    readonly dateDataWithOrWithoutRange: any[];
    ngOnInit(): void;
    updateData(): void;
    applyDimensions(): void;
    toggleFitContainer(event: any): void;
    selectChart(chartSelector: any): void;
    select(data: any): void;
    setInterpolationType(curveType: any): void;
    setColorScheme(name: any): void;
    onLegendLabelClick(entry: any): void;
    getCalendarData(): any[];
    calendarAxisTickFormatting(mondayString: string): string;
    calendarTooltipText(c: any): string;
    pieTooltipText({data}: {
        data: any;
    }): string;
    dollarValueFormat(c: any): string;
    getStatusData(): {
        name: string;
        value: number;
    }[];
    statusValueFormat(c: any): string;
    statusLabelFormat(c: any): string;
    pieLabelOptionChanged(): void;
}
