/// <reference path="../node_modules/awesome-typescript-loader/lib/runtime.d.ts" />
declare var _default: {
    arc: any;
    area: any;
    brush: any;
    brushX: any;
    brushY: any;
    event: any;
    extent: any;
    forceCollide: any;
    forceLink: any;
    forceManyBody: any;
    forceSimulation: any;
    forceX: any;
    forceY: any;
    format: any;
    interpolate: any;
    line: any;
    max: any;
    min: any;
    mouse: any;
    pie: any;
    range: any;
    rgb: any;
    selection: any;
    select: any;
    selectAll: any;
    scaleBand: any;
    scaleLinear: any;
    scaleOrdinal: any;
    scalePoint: any;
    scaleQuantile: any;
    scaleTime: any;
    shape: any;
    treemap: any;
    stratify: any;
    timeFormat: any;
    timeParse: any;
    timeHour: any;
};
export default _default;
