
import { EventEmitter, OnChanges, OnDestroy, AfterViewInit, ElementRef, NgZone, ChangeDetectorRef } from '@angular/core';
import { BaseChartComponent } from '../common/base-chart.component';
import { ViewDimensions } from '../common/view-dimensions.helper';
export declare class GaugeComponent extends BaseChartComponent implements OnChanges, OnDestroy, AfterViewInit {
    private element;
    private cd;
    view: any;
    scheme: any;
    customColors: any;
    gradient: boolean;
    value: number;
    min: number;
    max: number;
    units: string;
    bigSegments: number;
    smallSegments: number;
    clickHandler: EventEmitter<{}>;
    legendLabelClick: EventEmitter<any>;
    textEl: ElementRef;
    dims: ViewDimensions;
    valueDomain: any;
    valueScale: any;
    color: any;
    colors: Function;
    colorScale: any;
    transform: string;
    margin: number[];
    backgroundArc: any;
    valueArc: any;
    angleSpan: number;
    innerRadius: number;
    outerRadius: number;
    resizeScale: number;
    textTransform: string;
    ticks: any;
    constructor(element: ElementRef, cd: ChangeDetectorRef, zone: NgZone);
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    ngOnChanges(): void;
    update(): void;
    getValueDomain(): any[];
    getValueScale(): any;
    getTicks(): any;
    getTickPath(startDistance: any, tickLength: any, angle: any): any;
    displayValue(): string;
    scaleText(): void;
    onClick(data: any): void;
    setColors(): void;
}
