name: Build, Test, and Publish

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0

      - name: Enable Corepack
        run: corepack enable

      - name: Install Yarn
        run: corepack prepare yarn@4.9.2 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: npm run build:lib:prod
        env:
          CI: true

      - name: Test
        run: |
          yarn ci
        env:
          CI: true

      - name: Publish
        run: npm run publish:lib
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
